RestrauntIss/urls.py
from django.contrib import admin
from django.urls import path

from django.urls import include, path
urlpatterns = [

    path('review/', include('review.urls')),
    path('admin/', admin.site.urls),
]

review/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views
app_name = "review"

urlpatterns = [

    path('<int:catid>/', views.index, name='index'),
    path('', views.index, name='index'),
     path('rate', views.rate, name='rate'),
]

review/models.py
from django.db import models

# Create your models here.
from django.db import models


class Category(models.Model):
    Cname = models.CharField(max_length=100)
    Cid = models.IntegerField(primary_key=True)

    def __str__(self):
        # return '{}/{}'.format(self.Cname,self.Cid)
        return self.Cname


class Restaurant(models.Model):
    Cid = models.ForeignKey(Category,db_column='Cid', on_delete=models.Aggregate)
    Rname = models.CharField(max_length=200)
    Rid = models.IntegerField(primary_key=True)
    Radd=models.CharField(max_length=300)
    Rimage=models.CharField(max_length=300, null=True)
    Rdesc=models.CharField(max_length=300, null=True)

    def __str__(self):
        return '{}/{}/{}/{}/{}/{}'.format(self.Rid,self.Rname,self.Radd,self.Cid,self.Rimage,self.Rdesc)
       # return self.Rid

class Review(models.Model):
    Rvname = models.CharField(max_length=200)
    Rvid = models.IntegerField(primary_key=True)
    Rating = models.IntegerField(default=0)
    Rid = models.ForeignKey(Restaurant,db_column='Rid',on_delete=models.Aggregate)

    def __str__(self):
        return '{}/{}/{}/{}'.format(self.Rvid,self.Rvname,self.Rating,self.Rid)

class Comment(models.Model):
    Comid = models.IntegerField(primary_key=True)
    Ce_text = models.CharField(max_length=200)
    Rvid= models.ForeignKey(Review,db_column='Rvid',on_delete=models.Aggregate)

    def __str__(self):
        return '{}/{}/{}'.format(self.Comid,self.Ce_text,self.Rvid)

review/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse
from .models import Restaurant,Review,Comment,Category


def index(request,catid=0):
    context = {}
    category = Category.objects.all()

    cat_dict = dict()
    print(category.get(Cid=1))

    for dd in category:
        print(dd.Cid)
        cat_dict[dd.Cid] = dd.Cname

    rest = object

    if(catid==0):
        rest = Restaurant.objects.all()

    else:
        rest = Restaurant.objects.all().filter(Cid=catid)
    #
    context = {
        'cat': cat_dict,
        'restaurant': rest,
    }

    return render(request, 'home.html', context)


def rate(request):
    context={}
    print(" key of rest ")
    # if request.method == 'POST':
    c=request.POST['rkey']
    rating = request.POST['starkey']
    descc = request.POST['ratedesc']
    print(" id " +c+", rating "+rating+" , descript "+descc)

    context = {}
    category = Category.objects.all()

    cat_dict = dict()
    print(category.get(Cid=1))

    for dd in category:
        print(dd.Cid)
        cat_dict[dd.Cid] = dd.Cname

    rest = object

    rest = Restaurant.objects.all()


    context = {
        'cat': cat_dict,
        'restaurant': rest,
    }
    return render(request, 'home.html', context)


    # return render(request, 'home.html', context)

review/templates/home.html
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
      {% load static %}
     {% load staticfiles %}

    <meta charset="UTF-8">
    <title>Title</title>

  <link rel="stylesheet" href="{% static 'home.css' %}" />
 <script src="{% static 'home.js' %}"></script>

    <style>
body {font-family: Arial, Helvetica, sans-serif;}
/* The Modal (background) */
.modal {
  display: none; /* Hidden by default */
  position: fixed; /* Stay in place */
  z-index: 1; /* Sit on top */
  padding-top: 100px; /* Location of the box */
  left: 0;
  top: 0;
  width: 80%; /* Full width */
  height: 100%; /* Full height */
  overflow: auto; /* Enable scroll if needed */
  background-color: rgb(0,0,0); /* Fallback color */
  background-color: rgba(0,0,0,0.4); /* Black w/ opacity */
}
/* Modal Content */
.modal-content {
  background-color: #fefefe;
  margin: auto;
  padding: 20px;
  border: 1px solid #888;
  width: 80%;
}
/* The Close Button */
.close {
  color: #aaaaaa;
  float: right;
  font-size: 28px;
  font-weight: bold;
}
.close:hover,
.close:focus {
  color: #000;
  text-decoration: none;
  cursor: pointer;
}
		em {
			display: block;
			margin: .5em auto 2em;
			color: #bbb;
		}
		p, p a {
			color: #aaa;
			text-decoration: none;
		}
		p a:hover,
		p a:focus {
			text-decoration: underline;
		}
		p + p { color: #bbb; margin-top: 2em;}
		.detail {position: absolute; text-align: right; right: 5px; bottom: 5px; width: 80%;}
		a[href*="intent"] {
			display:inline-block;
			margin-top: 0.4em;
		}
		/*
		 * Rating styles
		 */
		.rating {
			width: 226px;
			height:80px;
			margin: 1em auto auto;
			font-size: 45px;
			overflow:override;
		}
		.rating a {
			float:right;
			color: #aaa;
			text-decoration: none;
			-webkit-transition: color .4s;
			-moz-transition: color .4s;
			-o-transition: color .4s;
			transition: color .4s;
		}
		.rating a:hover,
		.rating a:hover ~ a,
		.rating a:focus,
		.rating a:focus ~ a		{
			color: orange;
			cursor: pointer;
		}
		.rating2 {
			direction: rtl;
		}
		.rating2 a {
			float:none
		}
.text-area {
  width: 80%;
  margin:auto auto;
}
textarea {
  resize: none;
  display: inline-block;
  width: 100%;
  margin-top: 10px;
  padding: 10px;
  border: 1px solid #f7f7f7;
  background: #f7f7f7;
  border-radius: 5px;
  letter-spacing: 1.8px;
  font-weight: 300;
  border-color:black;
}
.button {
 	display:block;
  position:relative;
  padding:7px;
  margin:auto auto;
    width:20%;
  text-decoration:none;
  text-align:center;
  border:1px solid rgba(0,0,0,0.4);
  border-radius:0.2em;
  box-shadow:
    inset 0 1px 0 rgba(255,255,255,0.5),
    inset 0 20px 20px rgba(255,255,255,0.2),
    1px 2px 1px rgba(0,0,0,0.2),
    0 0 2px 8px rgba(50,50,50,0.1);
  transition:all 0.3s ease-out;
  background:orangered;
  font-family:Helvetica, sans-serif;
  font-size:1em;
  line-height:1.5em;
  font-weight:bold;
  color:rgba(255,255,255,0.8);
  text-shadow:0 -1px 0 rgba(0,0,0,0.3), 0 1px 0 rgba(255,255,255,0.2);
  -webkit-font-smoothing: subpixel-antialiased;
 }
  .orange { background:#d02211; }
</style>

</head>
<body>

<div id="myModal" class="modal">

  <!-- Modal content -->
  <div class="modal-content">
    <span class="close">&times;</span>

<h2>Rating the restaurant with description</h2>

<form action="{% url 'review:rate'  %}" method="post">
	<div class="rating rating2"><!--
		--><a href="#" title="Give 5 stars" onclick="rate5()">★</a><!--
		--><a href="#" title="Give 4 stars" onclick="rate4()">★</a><!--
		--><a href="#" title="Give 3 stars" onclick="rate3()">★</a><!--
		--><a href="#" title="Give 2 stars" onclick="rate2()">★</a><!--
		--><a href="#" title="Give 1 star" onclick="rate1()">★</a>
	</div>
{% csrf_token %}

    <input type="hidden" id="hidid" name="rkey">
<input type="hidden" id="starrate" name="starkey">
    <div class="text-area">
<p ></p>


        <textarea name="ratedesc"  id="status" rows="5" placeholder="What's on you mind?">


    </textarea>
        <br><br><br>
    <button type="submit"  class="button green"> Subscribe </button>

    </div>

  </form>


  </div>

</div>


<script>
// Get the modal
var modal = document.getElementById("myModal");
// Get the button that opens the modal
var btn = document.getElementById("myBtn");
// Get the <span> element that closes the modal
var span = document.getElementsByClassName("close")[0];
// When the user clicks the button, open the modal
<!--btn.onclick = function() {-->
  <!--modal.style.display = "block";-->
<!--}-->
function modelrate(){
modal.style.display = "block";
var x=document.getElementById("ridhid").value;
<!--alert(x);-->
}
// When the user clicks on <span> (x), close the modal
span.onclick = function() {
  modal.style.display = "none";
}
// When the user clicks anywhere outside of the modal, close it
window.onclick = function(event) {
  if (event.target == modal) {
    modal.style.display = "none";
  }
}
</script>


<script type='text/javascript' src='http://code.jquery.com/jquery-1.7.2.min.js'> </script>

</script>
<h1>Food Logo</h1>
 <h2>By Nyein Chan Kyaw Swar, Kay Thi Swe Tun, Ei Theingi Swe</h2>
  <nav>
      <ul style= "float:right">
          <li><a href="{% url 'review:index'  %}">Home</a></li>
          <li class="visited sub"><a href="#">Categories</a>
              <ul>

                  {% for key, values in cat.items %}
                <li id="catval" >

                <a href="{% url 'review:index' key %}">{{ values }}</a> </li>

                </li>
                {% endfor %}

              </ul>

          </li>
      </ul>

  </nav>

<p id="demo"></p>

  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
  <script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.11.2/jquery-ui.min.js"></script>

  <div id="displaywrap">
      <div id="logobx" style="display: block;">

      <img src="https://mir-s3-cdn-cf.behance.net/project_modules/disp/76ab2e19585305.562dce0bcf645.png"  class="logo"/>
      </div>

      <div class="mainpanel" style="display: block;">
          <img src="http://www.andrewjtullio.com/codepen/close.png" class="rmsclose">
          <div class="thumbbx">

              {% for val in restaurant %}
              <div class="roomthumb pqr" onclick="myfun('{{ val.Rname }}','{{ val.Rdesc }}','{{ val.Rid }}')">
                  <span id="rid" >{{ val.Rname }}</span>
                  <img style="width:232px;height:144px" src="{{val.Rimage}}">
              </div>


                {% endfor %}

          </div>
      </div>



      </div>

      <div class="leftinfobx petiteqn"  style="display: none;">
          <h2 id="Rname"></h2>

     <p id="desc"></p>


      <span class="rmamenslink"><span class="inroom"></span></span>

          <div class="btmlinks">
              <img src="http://www.andrewjtullio.com/codepen/back.jpg" class="btmback">
              <a target="_blank" onclick="modelrate()"><img style="width:110px;height:42px" src="http://www.clker.com/cliparts/x/F/9/x/I/k/review-button-png-hi.png" class="btmbooknow"></a>
          </div>

      </div>
  </div>
  <script src="{% static 'home.js' %}"></script>
<script>
function myfun(x,y,z) {
  var val=document.getElementById("rid").innerHTML;
  <!--alert( x+ "" );-->
  document.getElementById("Rname").innerHTML=x;
  document.getElementById("desc").innerHTML=y;
  document.getElementById("hidid").value=z;
 <!--document.getElementById("status").value=z;-->
}
function rate1(){
 document.getElementById("starrate").value=1;
}
function rate2(){
 document.getElementById("starrate").value=2;
}
function rate3(){
 document.getElementById("starrate").value=3;
}
function rate4(){
 document.getElementById("starrate").value=4;
}
function rate5(){
 document.getElementById("starrate").value=5;
}
</script>

</body>
</html>